### ISSUE TITLE
这个demo无法调起快手发布图片或者视频吗？

### ISSUE THREAD

**Issue by Cnjering** [KwaiSocial/KwaiSDK-Demo-Android#1]
返回错误
![Screenshot_20200708-114712_OpenSdkDemo](https://user-images.githubusercontent.com/40993038/86873500-fc045000-c110-11ea-895c-6c0628285add.jpg)

**Comment by fbiciacctv222** [comment]
请到快手开放平台https://open.kuaishou.com/platform申请您的appId并开启相应权限获取功能，demo的应用授予权限做了相应限制有的功能没有开启
