### ISSUE TITLE
requires a placeholder substitution but no value for <KWAI_APP_ID> is provided.

### ISSUE THREAD

**Issue by ChenJunXu** [KwaiSocial/KwaiSDK-Demo-Android#6]
你好，我将manifestPlaceholders的参数放在自己封装的 快手组件module下，但是 manifestPlaceholders 的参数设置异常，报错找不到 KWAI_APP_ID
![image](https://user-images.githubusercontent.com/19608552/128700053-5b6a5098-31bd-4441-b780-2398f7b436fd.png)

![image](https://user-images.githubusercontent.com/19608552/128699926-0f927825-26ea-4a30-8bab-028aec9804f1.png)

其他例如友盟等第三方sdk都可以在子module下设置。请问有什么办法可以解决？（不想放在 app 模块的 build.gradle 下）

**Comment by KwaiSocial** [comment]
当前仅支持manifestPlaceholders设置，此外manifestPlaceholders需要放在app的build.gradle中

**Comment by ChenJunXu** [comment]
manifestPlaceholders 没有限制只能放在 app 的 build.gradle 下，其他 module 组件都长期正常使用
