### ISSUE TITLE
sdk存在病毒

### ISSUE THREAD

**Issue by JarvanChen** [KwaiSocial/KwaiSDK-Demo-Android#7]
项目只接入sdk，不做任何调用com.github.kwaisocial:kwai-opensdk-withauth:3.0.4，华为应用商店上架app提示存在病毒，华为采用https://www.virustotal.com/该网站检测，病毒名称为riskware SPR/ANDR.Autoinst.A.Gen
当去掉依赖后，app不会报毒。

**Comment by KwaiSocial** [comment]
![image](https://user-images.githubusercontent.com/62368093/131434084-80dd1c0c-4b50-4d22-823b-211e10ecf657.png)
使用网址检查demo apk并未发现问题
